# Generated by Django 6.1.1 on 2026-09-17 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gestational_age_weeks', models.IntegerField()),
                ('eclampsia_severity', models.CharField(max_length=30)),
                ('haemorrhage_severity', models.CharField(max_length=30)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('prob_low', models.FloatField()),
                ('prob_medium', models.FloatField()),
                ('prob_high', models.FloatField()),
                ('model_backend', models.CharField(default='sklearn', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
